# Generated by Django 2.2.6 on 2020-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200417_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tag',
            field=models.CharField(max_length=30),
        ),
    ]
