# Generated by Django 2.2.6 on 2020-04-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
