# Generated by Django 2.2.6 on 2020-05-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200503_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='followers',
        ),
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
            preserve_default=False,
        ),
    ]
