# Generated by Django 2.2.6 on 2020-05-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='following',
            new_name='user',
        ),
    ]
