# Generated by Django 2.2.6 on 2020-05-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_users_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='followers',
        ),
    ]
