# Generated by Django 2.2.6 on 2020-05-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_users_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_users_followers_+', to='main.Users'),
        ),
    ]
