# Generated by Django 3.0.6 on 2020-05-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_task_taskimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
