# Generated by Django 2.2.6 on 2020-07-21 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagword', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Photos')),
                ('tagpar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TagHash')),
            ],
        ),
    ]
